name: Test frontend/web

on:
  push:
    paths:
      - 'source/frontend/web/**'
  pull_request:
    paths:
      - 'source/frontend/web/**'

jobs:
  tests:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: source/frontend/web

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: source/frontend/web/package-lock.json

      - name: npm install
        run:  npm ci
        
      - name: frontend-test
        run:  npm run test
